---
abstract: 'Collectd probe to consolidate data from'
author:
  - 'Fabien Wernli <wernli_workingat_in2p3.fr>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Collectd-Plugins-ConsoliDBIC
no_index:
  directory:
    - inc
    - share
    - t
requires:
  Collectd: 0
  Collectd::Unixsock: 0
  DBIx::Class: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.1001
